
##-----------------------------------------------------------------------##
#
# 	Titre: Makefile specifique.
# 
#	Auteurs: Bartholomew Chwalek
#
#
#	Description:
#
#
##-----------------------------------------------------------------------##


# Nom du projet, mot unique.

PROJECTNAME=main

# Fichers sources, tous les fichiers .cpp, .c, .S, etc.

PRJSRC= main.cpp

# Repertoire de base à tous les projets, position relative de /codeCommun/ au repertoire courant.

ROOTDIR=../../

# Position du ATMega16Defs pour les variables globales du micro.
include $(ROOTDIR)src/ATMega16Defs

# Position du Makefile_common.txt pour le makefile general.
include $(ROOTDIR)src/Makefile_common.txt